// flow-typed signature: 14ef7726c6040da2513c042e665023ca
// flow-typed version: <<STUB>>/application-config_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'application-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'application-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'application-config/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'application-config/index' {
  declare module.exports: $Exports<'application-config'>;
}
declare module 'application-config/index.js' {
  declare module.exports: $Exports<'application-config'>;
}
declare module 'application-config/test.js' {
  declare module.exports: $Exports<'application-config/test'>;
}
