// flow-typed signature: 155fc93641c8c0173c0b44f575fb95e8
// flow-typed version: <<STUB>>/osx-mouse_v^1.2.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'osx-mouse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'osx-mouse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'osx-mouse/index' {
  declare module.exports: $Exports<'osx-mouse'>;
}
declare module 'osx-mouse/index.js' {
  declare module.exports: $Exports<'osx-mouse'>;
}
