// flow-typed signature: 2de44c4acc9107746213354e8578e8af
// flow-typed version: <<STUB>>/react-electron-web-view_v^2.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-electron-web-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-electron-web-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-electron-web-view/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-electron-web-view/lib/ElectronWebView' {
  declare module.exports: any;
}

declare module 'react-electron-web-view/test/webview_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-electron-web-view/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-electron-web-view/gulpfile.babel'>;
}
declare module 'react-electron-web-view/lib/ElectronWebView.js' {
  declare module.exports: $Exports<'react-electron-web-view/lib/ElectronWebView'>;
}
declare module 'react-electron-web-view/test/webview_spec.js' {
  declare module.exports: $Exports<'react-electron-web-view/test/webview_spec'>;
}
