// flow-typed signature: 960f5b14a79214b98af70890a17ab1dd
// flow-typed version: <<STUB>>/redux-electron-store_v^0.4.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-electron-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-electron-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-electron-store/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/contains-remote-object' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/electronBrowserEnhancer' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/electronRendererEnhancer' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/getSubscribeFuncs' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/index' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/utils/__specs__/fill-shape-spec' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/utils/__specs__/object-merge-spec' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/utils/fill-shape' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/utils/filter-object' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/utils/object-difference' {
  declare module.exports: any;
}

declare module 'redux-electron-store/lib/utils/object-merge' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/constants' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/contains-remote-object' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/electronBrowserEnhancer' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/electronRendererEnhancer' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/getSubscribeFuncs' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/index' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/utils/__specs__/fill-shape-spec' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/utils/__specs__/object-merge-spec' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/utils/fill-shape' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/utils/filter-object' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/utils/object-difference' {
  declare module.exports: any;
}

declare module 'redux-electron-store/src/utils/object-merge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-electron-store/lib/constants.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/constants'>;
}
declare module 'redux-electron-store/lib/contains-remote-object.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/contains-remote-object'>;
}
declare module 'redux-electron-store/lib/electronBrowserEnhancer.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/electronBrowserEnhancer'>;
}
declare module 'redux-electron-store/lib/electronRendererEnhancer.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/electronRendererEnhancer'>;
}
declare module 'redux-electron-store/lib/getSubscribeFuncs.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/getSubscribeFuncs'>;
}
declare module 'redux-electron-store/lib/index.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/index'>;
}
declare module 'redux-electron-store/lib/utils/__specs__/fill-shape-spec.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/utils/__specs__/fill-shape-spec'>;
}
declare module 'redux-electron-store/lib/utils/__specs__/object-merge-spec.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/utils/__specs__/object-merge-spec'>;
}
declare module 'redux-electron-store/lib/utils/fill-shape.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/utils/fill-shape'>;
}
declare module 'redux-electron-store/lib/utils/filter-object.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/utils/filter-object'>;
}
declare module 'redux-electron-store/lib/utils/object-difference.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/utils/object-difference'>;
}
declare module 'redux-electron-store/lib/utils/object-merge.js' {
  declare module.exports: $Exports<'redux-electron-store/lib/utils/object-merge'>;
}
declare module 'redux-electron-store/src/constants.js' {
  declare module.exports: $Exports<'redux-electron-store/src/constants'>;
}
declare module 'redux-electron-store/src/contains-remote-object.js' {
  declare module.exports: $Exports<'redux-electron-store/src/contains-remote-object'>;
}
declare module 'redux-electron-store/src/electronBrowserEnhancer.js' {
  declare module.exports: $Exports<'redux-electron-store/src/electronBrowserEnhancer'>;
}
declare module 'redux-electron-store/src/electronRendererEnhancer.js' {
  declare module.exports: $Exports<'redux-electron-store/src/electronRendererEnhancer'>;
}
declare module 'redux-electron-store/src/getSubscribeFuncs.js' {
  declare module.exports: $Exports<'redux-electron-store/src/getSubscribeFuncs'>;
}
declare module 'redux-electron-store/src/index.js' {
  declare module.exports: $Exports<'redux-electron-store/src/index'>;
}
declare module 'redux-electron-store/src/utils/__specs__/fill-shape-spec.js' {
  declare module.exports: $Exports<'redux-electron-store/src/utils/__specs__/fill-shape-spec'>;
}
declare module 'redux-electron-store/src/utils/__specs__/object-merge-spec.js' {
  declare module.exports: $Exports<'redux-electron-store/src/utils/__specs__/object-merge-spec'>;
}
declare module 'redux-electron-store/src/utils/fill-shape.js' {
  declare module.exports: $Exports<'redux-electron-store/src/utils/fill-shape'>;
}
declare module 'redux-electron-store/src/utils/filter-object.js' {
  declare module.exports: $Exports<'redux-electron-store/src/utils/filter-object'>;
}
declare module 'redux-electron-store/src/utils/object-difference.js' {
  declare module.exports: $Exports<'redux-electron-store/src/utils/object-difference'>;
}
declare module 'redux-electron-store/src/utils/object-merge.js' {
  declare module.exports: $Exports<'redux-electron-store/src/utils/object-merge'>;
}
