// flow-typed signature: 51e1a9b4c93026ed002863a56c4e11bd
// flow-typed version: <<STUB>>/text-loader_v^0.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'text-loader/index' {
  declare module.exports: $Exports<'text-loader'>;
}
declare module 'text-loader/index.js' {
  declare module.exports: $Exports<'text-loader'>;
}
